development:
  adapter: redis
  url: redis://localhost:6379/1

test:
  adapter: testf

production:
  adapter: redis
  url: <%= ENV.fetch("REDIS_URL") { "redis://localhost:6379/1" } %>
  channel_prefix: message_me_production
